### ISSUE TITLE
GPL-406 Create COG barcodes

### ISSUE THREAD

**Issue by pjvv** [sanger/baracoda#1]
**User story**
As a dev team we would like to create a new, unique COG barcode when requested.

**Who the primary contacts are for this story**
Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:
1. an endpoint to request a new barcode, e.g. `/cog/new`

**Additional context**
COG barcodes to be generated according to: https://github.com/COG-UK/docs/blob/master/heron-barcodes.md

**Comment by emrojo** [comment]
Remaining tasks:

1. Solution provided has one unique sequence for all prefixes, but we want to have each prefix its own sequence, unless this assumption is not similar to cgap. **Waiting for answer**
2. Move configuration of prefixes and sequences into its own config file, but keeping database connection details into environment variables. **Waiting for answer on 1**
3. Prefix provided inside the url, instead of as a POST argument:
POST /prefix/TEST/new **TODO**
4. Provide an endpoint to obtain the current value for the prefix **In progress**
5. Docker configuration **Done**

**Comment by emrojo** [comment]
Current status of tasks:
1. Finally we will use one single sequence for all prefixes to be compatible with current barcodes generated. **Solved**
2. Configuration in a configuration/settings file. **Done**
3. Readapted endpoint to be POST /barcodes/<prefix>/new **Done**
4. Endpoint with current value GET /barcodes/<prefix/last **Done**
5. Docker build and tests done but need to add deployment config **In progress**

**Comment by emrojo** [comment]
Available endpoints:
* Generate a new barcode with prefix provided:
POST /barcodes/<prefix>/new
* Get last generated barcode for a prefix
GET /barcodes/prefix/last
* Get full list of prefixes
GET /prefixes
* Search a prefix by centre name
GET /search/prefixes?center=<name>
